from computer.config import RABBIT_MQ_CONN_STRING, REDIS_CONN_STRING


# Tasks
CELERY_IMPORTS = ('computer.mailing.tasks')

CELERY_BROKER_URL = RABBIT_MQ_CONN_STRING
CELERY_RESULT_BACKEND = REDIS_CONN_STRING
