"""Create Message model

Revision ID: 28eb2b5042fb
Revises: de302232ed30
Create Date: 2023-05-06 23:09:59.243930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28eb2b5042fb'
down_revision = 'de302232ed30'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('to', sa.Integer(), nullable=True),
    sa.Column('by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_by'), 'message', ['by'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=True)
    op.create_index(op.f('ix_message_to'), 'message', ['to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_to'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_by'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
