"""Added created at column in Message model

Revision ID: 7b4b3fa597c1
Revises: 28eb2b5042fb
Create Date: 2023-05-08 22:51:05.244662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4b3fa597c1'
down_revision = '28eb2b5042fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('created_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'created_at')
    # ### end Alembic commands ###
